config/routes.rb
Rails.application.routes.draw do
  resources :challenges
  devise_for :users, controllers: { sessions: 'users/sessions' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "home#index"

  post '/home/:run', to: 'home#run'
  get '/home/:switch_lang/:id', to: 'home#switch_lang'
end

app/models/challenge.rb
# == Schema Information
#
# Table name: challenges
#
#  id          :integer          not null, primary key
#  name        :string
#  description :string
#  raw_content :string
#  language    :string
#  point       :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Challenge < ApplicationRecord
    has_many :solutions
    accepts_nested_attributes_for :solutions
end

app/controllers/challenges_controller.rb
class ChallengesController < ApplicationController
  before_action :set_challenge, only: [:show, :edit, :update, :destroy]

  # GET /challenges
  # GET /challenges.json
  def index
    @challenges = Challenge.all
  end

  # GET /challenges/1
  # GET /challenges/1.json
  def show
  end

  # GET /challenges/new
  def new
    @challenge = Challenge.new
    @challenge.solutions.new
  end

  # GET /challenges/1/edit
  def edit
  end

  # POST /challenges
  # POST /challenges.json
  def create
    @challenge = Challenge.new(challenge_params)

    respond_to do |format|
      if @challenge.save
        format.html { redirect_to @challenge, notice: 'Challenge was successfully created.' }
        format.json { render :show, status: :created, location: @challenge }
      else
        format.html { render :new }
        format.json { render json: @challenge.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /challenges/1
  # PATCH/PUT /challenges/1.json
  def update
    respond_to do |format|
      if @challenge.update(challenge_params)
        format.html { redirect_to @challenge, notice: 'Challenge was successfully updated.' }
        format.json { render :show, status: :ok, location: @challenge }
      else
        format.html { render :edit }
        format.json { render json: @challenge.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /challenges/1
  # DELETE /challenges/1.json
  def destroy
    @challenge.destroy
    respond_to do |format|
      format.html { redirect_to challenges_url, notice: 'Challenge was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_challenge
      @challenge = Challenge.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def challenge_params
      params.require(:challenge).permit(:name, :description, :raw_content, :language, :point, solutions_attributes: [:content, :lang])
    end
end

app/helpers/challenges_helper.rb
module ChallengesHelper
end

app/views/challenges/_form.html.erb
<%= tinymce %>
<%= form_for(@challenge, html: { class: "form-horizontal", role: "form" }) do |f| %>
  <% if @challenge.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@challenge.errors.count, "error") %> prohibited this challenge from being saved:</h4>

      <ul>
      <% @challenge.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :name, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :description, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_area :description, :class => "tinymce", :rows => 40, :cols => 120 %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :solutions, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.fields_for :solutions, @challenge.solutions do |f_solution| %>
          <%= f_solution.text_field :content, :class => 'form-control' %>
      <% end %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :language, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :language, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :point, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.number_field :point, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/challenges/edit.html.erb
<div class="page-header">
  <%= link_to challenges_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @challenge, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing challenge</h1>
</div>

<%= render 'form' %>

app/views/challenges/index.html.erb
<div class="page-header">
  <%= link_to new_challenge_path, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New Challenge
  <% end %>
  <h1>Listing challenges</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
            <th>Name</th>
            <th>Description</th>
            <th>Raw content</th>
            <th>Language</th>
            <th>Point</th>
            <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% @challenges.each do |challenge| %>
      <tr>
          <td><%= challenge.name %></td>
          <td><%= challenge.description.slice(0, 20).concat('...') || '...' %></td>
          <td><%= challenge.raw_content %></td>
          <td><%= challenge.language %></td>
          <td><%= challenge.point %></td>
          <td><%= link_to 'Show', challenge %></td>
        <td><%= link_to 'Edit', edit_challenge_path(challenge) %></td>
        <td><%= link_to 'Destroy', challenge, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/challenges/new.html.erb
<div class="page-header">
  <%= link_to challenges_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New challenge</h1>
</div>

<%= render 'form' %>

app/views/challenges/show.html.erb
<%= tinymce %>
<div class="page-header">
  <%= link_to challenges_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_challenge_path(@challenge), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Show challenge</h1>
</div>

<dl class="dl-horizontal">
  <dt>Name:</dt>
  <dd><%= @challenge.name %></dd>

  <dt>Description:</dt>
  <dd><%= raw @challenge.description %></dd>

  <dt>Solutions:</dt>
  <dd>
    <% @challenge.solutions.each do |solution| %>
      <%= solution.content %>
    <% end %>
  </dd>

  <dt>Language:</dt>
  <dd><%= @challenge.language %></dd>

  <dt>Point:</dt>
  <dd><%= @challenge.point %></dd>

</dl>